### ISSUE TITLE
Неудачный запуск текущего релиза

### ISSUE THREAD

**Issue by Domaman202** [0Nera/BMOSP#3]
В ходе проведения тестирования (сборки и последующего запуска) свежесклонированного проекта мною было получена "ошибка страницы".
![Screenshot_20231024_202413](https://github.com/0Nera/BMOSP/assets/51743763/4f2667bb-8458-484c-81c4-de9c20336434)

**Comment by 0Nera** [comment]
Здравствуйте! О проблеме знаем и скоро исправим

Для решения в файле:
https://github.com/0Nera/BMOSP/blob/master/modules/helloworld/main.c#L10

Замените 10-ю строчку на
`return 0;`

**Comment by 0Nera** [comment]
В модулях ядра нельзя ссылаться на адрес без поправки на смещение. Поэтому возникает такая ошибка.
Проверяли прерывания на работоспособность.

**Comment by Domaman202** [comment]
Благодарю за помощь!

**Comment by Domaman202** [comment]
Интересный момент однако, после правок и повторной компиляции ничего не помогло (даже реклонировал проект и собрал снова).
![Screenshot_20231024_204101](https://github.com/0Nera/BMOSP/assets/51743763/703703d5-c9d6-4e95-b99a-4fff288ff15d)

**Comment by 0Nera** [comment]
Проделайте идентичную операцию в модуле music

**Comment by Domaman202** [comment]
Там и так 0 стоит :')

**Comment by 0Nera** [comment]
Лучше всего исключить модули из запуска. Для этого отредактируйте configs/limine.cfg

Сегодня вечером вышлю правки с исправлением

**Comment by Domaman202** [comment]
Хорошо, спасибо большое за помощь!

**Comment by 0Nera** [comment]
Исправлено в последнем изменении
